### ISSUE TITLE
Render Sprite Sheet and Splice Spritesheet should Expose the Execute Node button and also Save between sections

### ISSUE THREAD

**Issue by TheShankar** [Ttanasart-pt/Pixel-Composer#38]
Hi, I would like to respectfully request a feature.

I think nodes that have to Render could have that button "exposed" when added to groups, this way we could click the Render without having to go inside the Group itself (and without rendering everything)

And secondly, I think Render Sprite Sheet and Splice Spritesheet should save their memory between sections, if you save a file and open it up again, the contents of both nodes are empty.
Render Sprite Sheet is a very useful way for storing images in the "memory" and somewhat "prebaking them", which helps a lot to save processing on more complex scenes.

Thank you for your consideration!

**Comment by Ttanasart-pt** [comment]
Thanks for your suggestion. I've just added the first feature (expose execution to the group parent) in 1.13.4. 

For the second feature (caching between session). I might implement it, but probably on the newly added "cache" and "cache array" node, instead of Render Sprite Sheet. I think that make more sense name wise.

**Comment by TheShankar** [comment]
Thank you! The Cache works perfectly for what I was looking for, so for me it's all good!
