### ISSUE TITLE
App freeze with Shape Seperate sample project

### ISSUE THREAD

**Issue by rowanthemodder** [Ttanasart-pt/Pixel-Composer#6]
# Steps to Reproduce
- Click on Shape Seperate sample project
- Freeze

# Machine Specs
<details>
  <summary>Click to expand!</summary>

Processor AMD Ryzen 5 5600X 6-Core Processor

RAM 32.0 GB

System type 64-bit operating system, x64-based processor

GPU AMD Radeon RX 5700 XT

Driver version: 30.0.13037.1003

Driver date: 11/16/2021

DirectX version: 12 (FL 12.1)
</details>

# Versions
Pixel Composer 8.1
Windows 10

# Additional Notes
- Have to close the app with task manager
- Task manager shows that app doesn't increase in CPU, RAM, or GPU usage past normal

**Comment by Ttanasart-pt** [comment]
Sample projects are created in .6 version and a lot changed since then. I'll update the sample projects after version .9 (since that version will also change lot of things) so I will mark these issues as closed for now. In the next release (.8.2) I will just remove sample projects that doesn't work. Thank you for reporting in.
